CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    paid BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses(
    id SERIAL PRIMARY KEY,
    amount NUMERIC(12,2),
    category TEXT,
    date DATE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS loan (
    id SERIAL PRIMARY KEY,
    balance NUMERIC(12,2),
    installments JSONB,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

